<?php

namespace ContainerErCQX9Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TJDpnHxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tJDpnHx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tJDpnHx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::getCategory' => ['privates', '.service_locator.dJUcVDE', 'get_ServiceLocator_DJUcVDEService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.Ndw0NZG', 'get_ServiceLocator_Ndw0NZGService', true],
            'App\\Controller\\PostController::index' => ['privates', '.service_locator.k8qfJzx', 'get_ServiceLocator_K8qfJzxService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\CategoryController:getCategory' => ['privates', '.service_locator.dJUcVDE', 'get_ServiceLocator_DJUcVDEService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.Ndw0NZG', 'get_ServiceLocator_Ndw0NZGService', true],
            'App\\Controller\\PostController:index' => ['privates', '.service_locator.k8qfJzx', 'get_ServiceLocator_K8qfJzxService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\CategoryController::getCategory' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\PostController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoryController:getCategory' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\PostController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
