<?php

namespace ContainerErCQX9Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K8qfJzxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k8qfJzx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k8qfJzx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'catRepo' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'catRepo' => 'App\\Repository\\CategoryRepository',
            'repo' => 'App\\Repository\\PostRepository',
        ]);
    }
}
